apiVersion: v1
kind: Service
metadata:
  name: mlops-api-service
spec:
  selector:
    app: mlops-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP # La API solo es visible dentro del clúster por la Web