apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
  labels:
    app: 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
      - name: 
        image: gcr.io/icai2025/xxx:latest 
        ports:
        - containerPort: 8501
        env:
        - name: API_URL
          value: http://mlops-api-service:5000/predict 